website/images/accounts/urls.py
# accounts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

website/images/imager/urls.py
from django.contrib import admin
from django.urls import include,path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('imager/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

website/images/polls/urls.py
from django.urls import path
from . import views

app_name = "polls"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>', views.DetailView.as_view(), name='detail'),
    # POST: /polls/1/upvote,
    path('<int:image_id>/upvote', views.upvote, name='upvote'),
    # POST: /polls/1/downvote
    path('<int:image_id>/downvote', views.downvote, name='downvote'),
    # POST: /polls/1/comment
    path('<int:image_id>/comment', views.comment, name='comment')
]

website/images/accounts/models.py
from django.db import models

# Create your models here.

website/images/polls/models.py
from django.db import models

# Create your models here.

class Image(models.Model):
    name = models.CharField(max_length=200)
    url = models.CharField(max_length=1000)
    pub_date = models.DateTimeField('date published')
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class Comment(models.Model):
    image = models.ForeignKey(Image, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    comment = models.CharField(max_length=1000)
    pub_date = models.DateTimeField('date published')

website/images/accounts/views.py
# accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

website/images/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from polls.models import Image,Comment
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'image_list'

    def get_queryset(self):
        return Image.objects.all

class DetailView(generic.DetailView):
    model = Image
    template_name = 'polls/detail.html'

def upvote(request, image_id):
    return cast_vote(request, image_id, +1)

def downvote(request, image_id):
    return cast_vote(request, image_id, -1)

def cast_vote(request, image_id, score):
    image = get_object_or_404(Image, pk=image_id)
    image.votes += score
    image.save()
    return HttpResponseRedirect(reverse('polls:index'))

def comment(request, image_id):
    image = get_object_or_404(Image, pk=image_id)
    comment = image.comment_set.create(
        name = request.POST['name'],
        comment = request.POST['comment'],
        pub_date = timezone.now()
    )
    return HttpResponseRedirect(reverse('polls:index'))


#def index(request):
    #return render(request, 'polls/index.html')

website/images/polls/templates/polls/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<h1>{{ image.name }}</h1>
<h2>Score: {{ image.votes }}</h2>

<div style="width: 100%;">
    <div style="width: 45%; float:left;">
        <img src="{{ image.url }}" style="width: 100%;"/>
    </div>
    <div style="width: 45%; float:left;">
        {% if user.is_authenticated %}
            <form action="{% url 'polls:upvote' image.id %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Vote up">
            </form>
            <form action="{% url 'polls:downvote' image.id %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Vote down">
            </form>
            <form action="{% url 'polls:comment' image.id %}"
                    method="post">
                {% csrf_token %}
                <div>Nick: <input type="text" name="name"></div>
                <div>Comment: <input type="text" name="comment"></div>
                <div><input type="submit" value="Post comment"></div>
            </form>
            <div style="width=100%;">
                {% for comment in image.comment_set.all %}
                    <p>Nick: {{ comment.name }} <br/>
                        {{ comment.comment }} <br/>
                        Published at: {{ comment.pub_date }}
                    </p>
                    <hr>
                {% endfor %}
            </div>
        {% endif %}
    </div>
</div>

website/images/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<h1>Legendarna Stranica</h1>

<div>
{% if image_list %}
    {% for image in image_list %}
        <div style="width: 30%; float: left;">
            <p id="ime-slike">{{ image.name }}</p>
            <a href="{% url 'polls:detail' image.id %}">
                <img src="{{ image.url }}" 
                    style="width: 100%"/>
            </a>
            <p id="score">Score: {{ image.votes }}</p>
        </div>
    {% endfor %}
{% else %}
    <p>No images!</p>
{% endif %}
</div>

website/images/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

website/images/templates/home.html
<!-- templates/home.html-->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">logout</a></p>
  <p><a href="{% url 'password_reset' %}">reset password</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}

website/images/templates/signup.html
<!-- templates/signup.html -->
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}